export const GENRES = {
    NETFLIXORIGINALS: "Netflix Originals",
    TRENDING: "Trending",
    TOPRATED: "Top Rated",
    ADVENTURE: "Adventure",
    ANIMATION: "Animation",
    COMEDY: "Comedy",
    CRIME: "Crime",
    DOCUMENTARY: "Documentary",
    DRAMA: "Drama",
    FAMILY: "Family",
    FANTASY: "Fantasy",
    HISTORY: "History",
    HORROR: "Horror",
    MUSIC: "Music",
    MYSTERY: "Mystery",
    ROMANCE: "Romance",
    SCIENCE: "Science Fiction",
    SERIES: "TV Movie",
    THRILLER: "Thriller",
    WAR: "War",
    WESTERN: "Western",
    ACTION: "Action"
}

